Fix incorrect usage of natural logarithm intrinsic in MYNN surface layer scheme
The correct interface name for the natural logarithm intrinsic in Fortran is `LOG`.
`ALOG` is a specific interface that only takes a single precision argument, and its
exact name could also be implementation-defined.

Therefore, programmers should never rely on those specific interfaces.

This commit fixes the following error when compiling MYNN surface layer scheme in
double precision:

$ gfortran -c sf_mynn.F90
sf_mynn.F90:2036:14:

 2036 |  psimk=2*ALOG(0.5*(1+X))+ALOG(0.5*(1+X*X))-2.*ATAN(X)+2.*ATAN(1.)
      |              1
Error: In call to 'alog' at (1), type mismatch in argument 'x'; pass 'REAL(8)' to 'REAL(4)'